- config:
  - name: cloudkilat
  - base_url: http://www.cloudkilat.com/
  - currency_used: IDR
- product:
  - name: kilat_vm2
  - endpoint: layanan/kilat-vm-2.0
  - type: vm
  - data_display: card
  - content:
    - pricing:
      - spec_price:
        - extractor:
          - xpath: //ul[contains(@class,'price-list')]//li[not(contains(@class,'list-header'))]//h5[@class='price']
        - postprocess:
          - extract_numbers: null
      - spec_ram:
        - extractor:
          - xpath: //div[@class='spesifications']/div[1]//div[contains(@class,'value')]
        - postprocess:
          - extract_numbers: null
      - spec_vcpu:
        - extractor:
          - xpath: //div[@class='spesifications']/div[2]//div[contains(@class,'value')]
      - spec_ssd_volume:
        - extractor:
          - xpath: //div[@class='spesifications']/div[3]//div[contains(@class,'value')]
    - additional_features:
      - public_ip:
        - extractor:
          - xpath: //div[@class='spesifications']/div[4]//div[contains(@class,'value')]
      - lisensi_plesk:
        - extractor:
          - xpath: //div[@class='spesifications']/div[5]/div[contains(@class,'value')]
        - postprocess:
          - remove_strings: \n
          - remove_strings: \nEdition*
- product:
  - name: kilat_hosting
  - endpoint: layanan/kilat-hosting#fitur
  - type: hosting
  - data_display: card
  - content:
    - pricing:
      - spec_price:
        - extractor:
          - xpath: //div[@class="pricing pages"]//h1[@class="price"]
        - postprocess:
          - extract_numbers: null
      - spec_storage:
        - extractor:
          - xpath: //div[@class="product-single"]/div[@class="summary pages"]//div[@class="lists"]//li[2]/span
        - postprocess:
          - extract_after: \n
      - spec_email_account:
        - extractor:
          - xpath: //div[@class="product-single"]/div[@class="summary pages"]//div[@class="lists"]//li[5]/span
        - postprocess:
          - extract_after: \n
      - spec_free_domain:
        - extractor:
          - xpath: //div[@class="product-single"]/div[@class="summary pages"]//div[@class="lists"]//li[3]/span
        - postprocess:
          - extract_after: \n
      - spec_database:
        - extractor:
          - xpath: //div[@class="product-single"]/div[@class="summary pages"]//div[@class="lists"]//li[4]/span
        - postprocess:
          - extract_after: \n
- product:
  - name: kilat_domain
  - endpoint: layanan/kilat-domain
  - type: domain
  - data_display: card
  - content:
    - pricing:
      - spec_register_price:
        - extractor:
          - xpath: //table[@class="price-table"]/tbody/tr/td[2]
        - postprocess:
          - extract_numbers: 
      - spec_domain:
        - extractor:
          - xpath: //table[@class="price-table"]/tbody/tr/td[1]
      - spec_transfer_price:
        - extractor:
          - xpath: //table[@class="price-table"]/tbody/tr/td[4]
        - postprocess:
          - extract_numbers: 
      - spec_price_extend:
        - extractor:
          - xpath: //table[@class="price-table"]/tbody/tr/td[4]
        - postprocess:
          - extract_numbers: 