- config:
  - name: qwords
  - base_url: https://www.qwords.com/
  - currency_used: IDR
- product:
  - name: Virtual_Private_Server
  - endpoint: vps-indonesia/vps-ssd
  - type: vm
  - data_display: slider
  - dump_to_database: true
  - action_chains:
    - slider_handler:
      - run: 6
      - move_to_element:
        - to_element:
          - xpath: //div[@id='slider']/span
        - move_to_window_center: true
      - click:
        - on_element:
          - xpath: //div[@id='slider']/span
        - move_to_window_center: true
      - drag_and_drop_by_offset:
        - source:
          - xpath: //div[@id='slider']/span
        - xoffset: 100
        - yoffset: 0
        - move_to_window_center: true
  - content:
    - pricing:
      - spec_price:
        - extractor:
          - xpath: //span[@id='d-harga']
      - spec_ssd_volume:
        - extractor:
          - xpath: //span[@id='d-disk-space']
      - spec_ram:
        - extractor:
          - xpath: //span[@id='d-ram']
      - spec_vcpu:
        - extractor:
          - xpath: //span[@id='d-cpu']
      - spec_public_ip:
        - extractor:
          - xpath: //span[@id='d-ipaddress']
      - spec_os:
        - extractor:
          - xpath: //span[@id='d-operatingsystem']
- product:
  - name: Virtual_Private_Server
  - endpoint: vps-indonesia/
  - type: vm
  - data_display: slider
  - dump_to_database: true
  - action_chains:
    - slider_handler:
      - run: 6
      - move_to_element:
        - to_element:
          - xpath: //div[@id='slider']/span
        - move_to_window_center: true
      - click:
        - on_element:
          - xpath: //div[@id='slider']/span
        - move_to_window_center: true
      - drag_and_drop_by_offset:
        - source:
          - xpath: //div[@id='slider']/span
        - xoffset: 100
        - yoffset: 0
        - move_to_window_center: true
  - content:
    - pricing:
      - spec_price:
        - extractor:
          - xpath: //span[@id='d-harga']
        - postprocess:
          - extract_numbers: 
      - spec_storage_volume:
        - extractor:
          - xpath: //span[@id='d-disk-space']
      - spec_ram:
        - extractor:
          - xpath: //span[@id='d-ram']
      - spec_vcpu:
        - extractor:
          - xpath: //span[@id='d-cpu']
      - spec_public_ip:
        - extractor:
          - xpath: //span[@id='d-ipaddress']
      - spec_os:
        - extractor:
          - xpath: //span[@id='d-operatingsystem']
- product:
  - name: Virtual_Private_Server
  - endpoint: vps-indonesia/vps-kvm
  - type: vm
  - data_display: slider
  - dump_to_database: true
  - action_chains:
    - slider_handler:
      - run: 6
      - move_to_element:
        - to_element:
          - xpath: //div[@id='slider']/span
        - move_to_window_center: true
      - click:
        - on_element:
          - xpath: //div[@id='slider']/span
        - move_to_window_center: true
      - drag_and_drop_by_offset:
        - source:
          - xpath: //div[@id='slider']/span
        - xoffset: 200
        - yoffset: 0
        - move_to_window_center: true
  - content:
    - pricing:
      - spec_price:
        - extractor:
          - xpath: //span[@id='d-harga']
        - postprocess:
          - extract_numbers: 
      - spec_ssd_volume:
        - extractor:
          - xpath: //span[@id='d-disk-space']
      - spec_ram:
        - extractor:
          - xpath: //span[@id='d-ram']
      - spec_vcpu:
        - extractor:
          - xpath: //span[@id='d-cpu']
      - spec_public_ip:
        - extractor:
          - xpath: //span[@id='d-ipaddress']
      - spec_os:
        - extractor:
          - xpath: //span[@id='d-operatingsystem']
- product:
  - name: Hosting_Value_Performance
  - endpoint: 'hosting-indonesia/value-performance/'
  - type: hosting
  - data_display: card
  - skip_first_data: False
  - dump_to_database: True
  - content:
    - pricing:
      - spec_price:
        - extractor:
          - xpath: //div[@class="price-plan__card"]/label
        - postprocess:
          - extract_numbers:
      - spec_storage:
        - extractor:
          - xpath: //ul[contains(@class,"price-plan")]//li[1]
        - postprocess:
          - extract_before: "\n"
      - spec_email_account:
        - extractor:
          - xpath: //div[contains(@id,"accordion")]//li[1]
          - attribute: innerHTML
        - postprocess:
          - extract_numbers:
      - spec_ftp_user:
        - extractor:
          - xpath: //div[contains(@id,"accordion")]//li[2]
          - attribute: innerHTML
        - postprocess:
          - extract_numbers:      
      - spec_subdomain:
        - extractor:
          - xpath: //div[contains(@id,"accordion")]//li[3]
          - attribute: innerHTML
        - postprocess:
          - extract_numbers:      
      - spec_database:
        - extractor:
          - xpath: //div[contains(@id,"accordion")]//li[4]
          - attribute: innerHTML
        - postprocess:
          - extract_numbers:
      - spec_free_domain:
        - extractor:
          - xpath: //div[contains(@id,"accordion")]//li[5]
          - attribute: innerHTML
        - postprocess:
          - extract_after: ":"          
    - additional_features:
      - php_memory: 
        - extractor:
          - xpath: //div[contains(@id,"accordion")]//li[6]
          - attribute: innerHTML
        - postprocess:
          - extract_after: ":"          
      - website_builder:
        - extractor:
          - xpath: //ul[contains(@class,"price-plan")]//li[6]
- product:
  - name: Hosting_High_Performance
  - endpoint: hosting-indonesia/high-performance-cloud-hosting/
  - type: hosting
  - data_display: slider
  - dump_to_database: true
  - action_chains:
    - slider_handler:
      - run: 13
      - move_to_element:
        - to_element:
          - xpath: //div[@id='slider']/span
        - move_to_window_center: true
      - click:
        - on_element:
          - xpath: //div[@id='slider']/span
        - move_to_window_center: true
      - drag_and_drop_by_offset:
        - source:
          - xpath: //div[@id='slider']/span
        - xoffset: 100
        - yoffset: 0
        - move_to_window_center: true
  - content:
    - pricing:
      - spec_price:
        - extractor:
          - xpath: //span[@id="d-harga"]
        - postprocess:
          - extract_numbers: null
      - spec_storage:
        - extractor:
          - xpath: //span[@id="d-disk-space"]
        - postprocess:
          - remove_strings: ':'
      - spec_free_domain:
        - extractor:
          - xpath: //span[@id="d-domain"]
      - spec_subdomain:
        - extractor:
          - xpath: //span[@id="d-subdomain"]
      - spec_email_account:
        - extractor:
          - xpath: //span[@id="d-akunemail"]
        - postprocess:
          - extract_numbers: null
      - spec_ftp_user:
        - extractor:
          - xpath: //span[@id="d-akunftp"]
      - spec_database:
        - extractor:
          - xpath: //span[@id="d-database"]
      - spec_control_panel:
        - extractor:
          - xpath: //span[@id="d-websitebuilder"]
      - spec_spam_filter:
        - extractor:
          - xpath: //*[@id="d-spamfilter"]
    - additional_features:
      - inodes:
        - extractor:
          - xpath: //span[@id="d-inodes"]
      - entry_proses:
        - extractor:
          - xpath: //span[@id="d-entryproses"]
      - i/o:
        - extractor:
          - xpath: //span[@id="d-ioinput"]
      - php_memory:
        - extractor:
          - xpath: //span[@id="d-phpmemory"]
- product:
  - name: Hosting_medium_performance
  - endpoint: /hosting-indonesia/medium-performance-high-storage/
  - type: hosting
  - data_display: card
  - dump_to_database: true
  - action_chains:
    - click_tab:
      - run: 1
      - move_to_element:
        - to_element:
          - xpath: //a[@id="nav2-tab"]
        - move_to_window_center: false
      - click:
        - on_element:
          - xpath: //*[@id="nav2-tab"]
        - move_to_window_center: false
  - content:
    - pricing:
      - spec_price:
        - extractor:
          - xpath: //table[@id="product"]/tbody/tr[1]/th/h5
        - postprocess:
          - extract_numbers: null
      - spec_storage:
        - extractor:
          - xpath: //table[@id="product"]/tbody/tr[5]/td/div[2]
      - spec_free_domain:
        - extractor:
          - xpath: //table[@id="product"]/tbody/tr[11]/td/div[2]
      - spec_subdomain:
        - extractor:
          - xpath: //table[@id="product"]/tbody/tr[9]/td/div[2]
      - spec_email_account:
        - extractor:
          - xpath: //*[@id="product"]/tbody/tr[8]/td/div[2]
      - spec_ftp_user:
        - extractor:
          - xpath: //*[@id="product"]/tbody/tr[8]/td/div[2]
      - spec_database:
        - extractor:
          - xpath: //table[@id="product"]/tbody/tr[10]/td/div[2]
      - spec_control_panel:
        - extractor:
          - xpath: //*[@id="product"]/tbody/tr[13]/td/div[2]
      - spec_spam_filter:
        - extractor:
          - xpath: //*[@id="product"]/tbody/tr[14]/td/div[2]
- product:
  - name: domain_qwords
  - endpoint: 'domain-name/'
  - type: domain
  - data_display: card
  - dump_to_database: True
  - skip_first_data: True
  - action_chains:
    - radio_ontrol:
      - run: 1
      - move_to_element:
        - to_element:
          - xpath: '//*[@id="inputAll"]'
        - move_to_window_center: true
      - click:
        - on_element:
          - xpath: '//*[@id="inputAll"]'
        - move_to_window_center: False
  - content:
    - pricing:
      - spec_register_price:
        - extractor:
          - xpath: //*[@id="users"]/ul/li/span[2]/span[3]
        - postprocess:
          - extract_after: "/"
          - extract_numbers:
      - nm_domain_type:
        - extractor:
          - xpath: //*[@id="users"]/ul/li/span[1]/a