- config:
  - name: cloudkilat
  - base_url: "http://www.cloudkilat.com/"
  - currency_used: "IDR"
- product:
  - name: kilat_vm2
  - endpoint: 'layanan/kilat-vm-2.0'
  - type: vm
  - data_display: card
  - content:
      - pricing:
          - spec_price:
              - extractor:
                  - xpath: //ul[contains(@class,'price-list')]//li[not(contains(@class,'list-header'))]//h5[@class='price']
              - postprocess:
                  - extract_numbers:
                  - math: {'operator': '*', y: 12}
          - spec_ram:
              - extractor:
                  - xpath: //div[@class='spesifications']/div[1]//div[contains(@class,'value')]
              - postprocess:
                  - extract_numbers:
          - spec_vcpu:
              - extractor:
                  - xpath: //div[@class='spesifications']/div[2]//div[contains(@class,'value')]
          - spec_ssd_volume:
              - extractor:
                  - xpath: //div[@class='spesifications']/div[3]//div[contains(@class,'value')]
      - additional_features:
          - public_ip:
              - extractor:
                  - xpath: //div[@class='spesifications']/div[4]//div[contains(@class,'value')]
          - lisensi_plesk:
              - extractor:
                  - xpath: //div[@class='spesifications']/div[5]/div[contains(@class,'value')]
              - postprocess:
                  - remove_strings: \n
                  - remove_strings: \nEdition*