- config:
  - name: rumah_web
  - base_url: "https://www.rumahweb.com/"
  - currency_used: "IDR"
- product:
  - name: profesional_hosting
  - endpoint: 'hosting-murah/#profesional'
  - type: hosting
  - data_display: card
  - skip_first_data: true
  - action_chains:
      - change_tab:
          - move_to_element:
              - to_element:
                  - xpath: '//a[@href="#profesional"]'
          - click:
              - on_element:
                  - xpath: '//a[@href="#profesional"]'
  - content:
      - pricing:
          - spec_price:
              - extractor:
                  - xpath: '//*[@id="profesional"]/div/div[*]/div/p[7]/span/strong'
              - postprocess:
                  - extract_convert_float:
          - spec_storage:
              - extractor:
                  - xpath: '//*[@id="profesional"]/div/div[*]/div/ul/li[1]/strong'
          - spec_email_account:
              - extractor:
                  - xpath: '//*[@id="profesional"]/div/div[*]/div/ul/li[3]/strong'
          - spec_free_domain:
              - extractor:
                  - xpath: '//*[@id="profesional"]/div/div[*]/div/ul/li[4]/strong'
          - spec_database:
              - extractor:
                  - xpath: '//*[@id="profesional"]/div/div[*]/div/ul/li[5]/strong'
      - additional_features:
          - traffic:
              - extractor:
                  - xpath: '//*[@id="profesional"]/div/div[*]/div/ul/li[2]/strong'
          - web_builder:
              - extractor:
                  - xpath: '//*[@id="profesional"]/div/div[*]/div/ul/li[7]/strong'
- product:
  - name: enterprise_hosting
  - endpoint: 'hosting-murah/#enterprise'
  - type: hosting
  - data_display: card
  - skip_first_data: true
  - action_chains:
      - change_tab:
          - move_to_element:
              - to_element:
                  - xpath: '//a[@href="#enterprise"]'
          - click:
              - on_element:
                  - xpath: '//a[@href="#enterprise"]'
  - content:
      - pricing:
          - spec_price:
              - extractor:
                  - xpath: '//*[@id="enterprise"]/div/div[*]/div/p[7]/span/strong'
              - postprocess:
                  - extract_convert_float:
          - spec_storage:
              - extractor:
                  - xpath: '//*[@id="enterprise"]/div/div[*]/div/ul/li[1]/strong'
          - spec_email_account:
              - extractor:
                  - xpath: '//*[@id="enterprise"]/div/div[*]/div/ul/li[3]/strong'
          - spec_free_domain:
              - extractor:
                  - xpath: '//*[@id="enterprise"]/div/div[*]/div/ul/li[4]/strong'
          - spec_database:
              - extractor:
                  - xpath: '//*[@id="enterprise"]/div/div[*]/div/ul/li[5]/strong'
      - additional_features:
          - web_builder:
              - extractor:
                  - xpath: '//*[@id="enterprise"]/div/div[*]/div/ul/li[7]/strong'
- product:
  - name: vps_indonesia
  - endpoint: '/vps-indonesia/'
  - type: vm
  - data_display: card
  - content:
      - pricing:
          - spec_price:
              - extractor:
                  - xpath: //div[@class="vps-paket"]//div[@class="row"]//em
              - postprocess:
                  - extract_numbers:
          - spec_ram:
              - extractor:
                  - xpath: //div[@class="vps-paket"]//div[@class="row"]//li[@class="ram"]
              - postprocess:
                  - extract_numbers:
          - spec_vcpu:
              - extractor:
                  - xpath: //div[@class="vps-paket"]//div[@class="row"]//ul[@class="details"]/li[1]
          - spec_clock:
              - extractor:
                  - xpath: //div[@class="vps-paket"]//div[@class="row"]//li[@class="cpu"]//strong          
          - spec_storage_volume:
              - extractor:
                  - xpath: //div[@class="vps-paket"]//div[@class="row"]//li[@class="storage"]//strong
          - spec_storage_volume:
              - extractor:
                  - xpath: //div[@class="vps-paket"]//div[@class="row"]//li[@class="storage"]//strong                  
      - additional_features:
          - iops:
              - extractor:
                  - xpath: //div[@class="vps-paket"]//div[@class="row"]//li[@class="iops"]//strong
          - vswap:
              - extractor:
                  - xpath: //div[@class="vps-paket"]//div[@class="row"]//ul[@class="details"]/li[2]/strong
          - Plesk:
              - extractor:
                  - xpath: //div[@class="vps-paket"]//div[@class="row"]//ul[@class="details"]/li[5]
